highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyller.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /
title: Gary Magneson's Resume
name: Gary Magneson
email: gary@magneson.com
email_full: mailto:gary@magneson.com
website: github.io/GaryMagneson
website_full: https://GaryMagneson.github.io/
github: GaryMagneson
twitter: GMagneson
linkedin: gary-magneson-10094545
tel: +1 515 661 3584
tel_full: tel:+15156613584
google_maps: 'https://www.google.com/maps/place/7123+N+Valley+Dr,+Urbandale,+Iowa++50322'
address:
  street: 7123 N Valley Dr
  postcode: 50322
  city: Urbandale
  state: Iowa
  country: USA

# needed for travis-ci build
exclude: [vendor]
